### ISSUE TITLE
Precision of exported geometry

### ISSUE THREAD

**Issue by cdyk** [cdyk/rvmparser#23]
Created a new issue for reply of @xiaofan-start in issue https://github.com/cdyk/rvmparser/issues/16 :

I use your code to parse a rvm file and convert it to a obj file, but the accuracy of the model mesh is slightly lower for me. Can I set the model mesh accuracy during conversion?

**Comment by cdyk** [comment]
Can you elaborate on what kind of accuracy you are concerned about?

A) The `tolerance` option controls how dense the geomtry is tessellated. If shapes is too faceted, setting a lower tolerance will help.

B) If the geometry is positioned far away, single-precision float might be insufficient. The data in RVM files are single precision, the tessellated is done around a local origin, so there should be no relevant loss there.

However, obj-files don't support node hierarchies, so all geometries is positioned and rotated before export, and if the position of the geometry is far from the origin, you probably get artifacts. I believe this can be remedied to do calculate this in double precision during export and store the full double precision, in addition the exported model could be centered so float precisions works better.

You can also try out https://github.com/cdyk/rvmparser/tree/export-gltf and look at gltf file (see https://github.com/cdyk/rvmparser/pull/20) for caveats, as the gltf file format supports node hierarchies (and it can center the model)

**Comment by xiaofan-start** [comment]
Dear cdyk,
Thank you very much!
I am concerned about the number of faces of geometry.There are a lot of  small mesh models in my file.The default tolerance unsuited and I am setting the value of the tolerance to get better result.

**Comment by cdyk** [comment]
Great! Is your problem is fully solved?

**Comment by xiaofan-start** [comment]
Dear cdky,
It works well.
But I have a question about the glb file.I use your code to parse a rvm file and get a glb file. I try to load the glb file by Print 3D and Three.js but failed.I don't know the reason for it.And I would like to know the way to load the glb file.Thank you very much.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Christopher ***@***.***&gt;; 
发送时间: 2021年4月24日(星期六) 晚上9:49
收件人: ***@***.***&gt;; 
抄送: "ShuaiShuai ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cdyk/rvmparser] Precision of exported geometry (#23)





 
Great! Is your problem is fully solved?

**Comment by cdyk** [comment]
The glb container format should be well supported, I loaded my test models in Blender with no problems.

You can also test your file with https://github.khronos.org/glTF-Validator/ to verify that the structure of the file is correct. If validation fails, please open a bug issue.

I have also opened issue https://github.com/cdyk/rvmparser/issues/25 for producing pure gltf-files (without glb container), which might be more widely supported.
