### ISSUE TITLE
Has the behaviour of RVMparser been changed ?

### ISSUE THREAD

**Issue by anadana** [cdyk/rvmparser#34]
Hy Christopher
We discussed rvmparser on linkedin three years ago.
I don't know if you remember that discussion
I have implemented a module in rvmparser to simplify the PDMS hierarchy. This module regenerates an rvm file by grouping the geometry at a level passed in parameter. 
After incorporating this module in the latest version of RVMparser in order to take advantage of the export functionality in gltf format, I notice that the reading of simplified rvm files does not work anymore. Has the import algorithm of the rvm files changed?
Thanks for your answer.

**Comment by cdyk** [comment]
Hi,

Yes, there has been some changes as I have learned more about the RVM format:
- len field in chunk header reinterpreted as offset-to-next-chunk
- if cntb chunk has a version greater than 2, it has an extra word with transparency info
- support for COLR, INSU, and OBST chunks.

In what way does reading of the simplified RVM file fail?

**Comment by anadana** [comment]
Hi Christopher,
Here is the error I get when I run rvmParser on a streamlined RVM file

*Failed to parse E:\CAO\Home\HLF1025Export_Roombat_sbfi_PENE-compact.rvm:
After chunk PRIM, expected offset 0x180, current offset is 0x420c*

I think there is a problem with the offset control of the PRIM chunk

After commenting the line 323 of parserRVM.cpp
if (!verifyOffset(ctx, "PRIM", base_ptr, curr_ptr,
expected_next_chunk_offset)) return nullptr;
The glb file seems to be correctly generated

Have you an idea about this problem

Sincerely

**Comment by cdyk** [comment]
Hi,

The offset field is the offset of the next chunk. The PRIM chunk can vary in size depending on what kind of primitive is contained.

Are you sure you calculate this correctly when generating the file and that the problem is in rvmparser?

This offset is only needed to verify file integrity (and it could be used to skip unknown chunks), so the test is really not essential for rvmparser to work. So it can be skipped as a work-around

**Comment by VegarRingdalAibel** [comment]
I also go this error while trying it on a large file at work.
Tried to produce new RVM file on just that site, but was not able to reproduce error.
So my issue might be something auto coloring they do during the export with PDMS PML script/MAC files.

@anadana Did you find out more btw ?
Looks like commenting out the verify part helped, but ran into memory issues due to file size (4,7 gig RVM 😄 )

Think I need to figure out how to read main 1 site, then generate glb, clear memory, then read/produce next site/main group.
Just need to learn c++ first 😂

**Comment by cdyk** [comment]
The RVM offset fields are 32 bits, so max offset is ~4.2GB, so I guess a 4.7GB file gets a wrap-around. 

Might be sufficient to replace line 101 in ParserRVM.cpp with 

`uint32_t current_offset = uint32_t(curr_ptr - base_ptr);`

as the comparison is then done in 32 bits and not 64 bits.

**Comment by VegarRingdalAibel** [comment]
@cdyk 

Thx, Ill give it a try, will post back how it goes in a few minutes

Update: (this was a quick update, never hit send on first post 😂 )
Looks like I got a few more errors while parsing

Ended up with this duing the `gltf` export

`Assertion failed: ctx->dataBytes + size <= std::numeric_limits<uint32_t>::max(), file D:\rvmparser\src\ExportGLTF.cpp`

**Comment by VegarRingdalAibel** [comment]
Changing line 64 i in ExportGLTF.cpp helped.
Ended up with a 7,9gig gltf 😂 

`assert(ctx->dataBytes + uint32_t(size) <= std::numeric_limits<uint32_t>::max());`

**Comment by VegarRingdalAibel** [comment]
@cdyk 

Btw, in ParserRVM I ended up with changing line 102 to
`if (uint32_t(current_offset) == expected_next_chunk_offset) {`

Else snprintf gave errors, dint know anything about formatting, so was easier for me to do it this way.

**Comment by cdyk** [comment]
The glb container format has a 32-bit length field in the header, i.e. a max size of 4GB, and all references into the binary blob is 32 bits as well, so that file is probably invalid. Handling more than 4GB of geometry requires splitting the gltf-data into multiple files, which rvmparser doesn't do.

I would suggest splitting the rvm-file into layers/zones so that each piece is more manageable.

**Comment by VegarRingdalAibel** [comment]
Trying to use existing files generated by pipline to naviswork I have no control of/can not change. Only access to RVM file.
So will probably need to modify the rvm parser to generate 1 glb file per site, who knows maybe Im very lucky... will just take a very long time to figure out while trying to learn :-)

Or just generate json file/pure buffer file and parse that into more manageable pieces.

@cdyk Btw, thank you for taking the time to respond. 👍 🥇

**Comment by cdyk** [comment]
With no control of the input file, splitting into layers would be the first thing I would try. If you're lucky, the files have a suitable attribute you can use for splitting (use --output-json to create a massive json-file with all metadata) or there is a suitable prefix in the name (use --output-txt to get a text file with all node names).

If you look at DiscardGroups.cpp, that code discards the part of the node hierarchy that doesn't the condition tested on line 47. In this case, it is just a list of groups to discard read from a text file, but an alternative would be to check if the group name starts or does not start with a given prefix.

Another test one could do is to check if the node has a given attribute, and if so, check if it its value matches. If it matches or does not have the attribute, process the node and recurse into the children, otherwise just return from the function.

Another place to attach is in the ExportGLTF.cpp filem, in the processGroup function. This function traverses the hierarchy and sets up the data to write. You could have a test on the start whether or not you want to export this part of the hierarchy (e.g. check prefix of name or attribute). If you wrap the exportGLTF function body into a loop, you can directly export all layers you specify one-by-one.

A really simple predicate is, if the hierarchy "split point" you want is always at a given level in the hierarchy, is to keep track of recursion depth when you call processGroup, and when you are at the given depth, only recurse into the n'th child.

**Comment by VegarRingdalAibel** [comment]
Thank you. 👍

**Comment by vegarringdal** [comment]
FYI

Got it to do what i needed, modified it a lot to my needs in main/gltf export.
Wanted the buffer as pure buffer file, gltf meta as json I could read with javascript to process the data more/merging etc, that why we have a few edits in the exportgltf..

https://github.com/VegarRingdalAibel/rvmparser/blob/file_per_site/src/main.cpp#L280-L306

When and if I get time to clean up more I will :-) 
Yes, some parts might be weird.. but Im pretty new to c++ :-)

Though I could post it here just incase it can help someone else too.

@cdyk Thanks again for taking the time to respond, really helped a lot. 🥇

**Comment by vegarringdal** [comment]
@cdyk 

Hi, have you ever seen something like this ?
Ive kinda limited it down to site of RVM file, but its getting harder to get closer to item atm
Figured I could ask, since I knew what was wrong last time :-)

![image](https://user-images.githubusercontent.com/2901416/194171811-1b6925f0-81e6-4f86-b43d-4fad21f74156.png)

**Comment by cdyk** [comment]
It is libtess that breaks for some reason. It is used to triangulate polygon faces of facetGroup primitives.

You can try to go up in the stack trace to triangulationFactory::facetGroup and look at the polygon that is triangulated.

Either the polygon is degenerated in some way that libtess doesn't like (eg duplicate or colin ear points or nan's etc) or data points to uninitialized memory (0xcdcdcd..), which might be a bug in rvmparser.

**Comment by VegarRingdalAibel** [comment]
@cdyk 
Does this tell you anything ?
Looks like vertices is nan
Also searched up same item in naviswork converted file (image 2 & 3) and it looks like its a item without any geometry

![image](https://user-images.githubusercontent.com/94840334/194220812-f0f0347e-179e-49eb-8a83-9c9d8a14d612.png)



![image](https://user-images.githubusercontent.com/94840334/194222327-357fa8c9-7b90-4015-bc57-2b07b08364e9.png)
![image](https://user-images.githubusercontent.com/94840334/194222510-7704a0ad-fdb0-436e-bced-c58012f4bfa0.png)

**Comment by vegarringdal** [comment]
I might get around the issue doing this..
Might not be the best place to do it, but it did not break down now. Need to run it through some other post progressing tools we use to know for sure. Hoping for the best :-)

![image](https://user-images.githubusercontent.com/2901416/194229440-35a92978-af72-4071-a2ce-2877481da12e.png)

**Comment by VegarRingdalAibel** [comment]
Looks like this solved my issues. No more segfaults

**Comment by cdyk** [comment]
If the input data contains nan, it is just garbage, so IMO one should just discard it (possibly with a warning), ie what you have done.

I think I would have had the check when reading the rvm file, to filter it out as early as possible.

Btw, it looks like your code only checks the first component of the first vertex in each contour. Also, std::isfinite checks both nan and infinity, infinity in vertex positions isn't very useful either.

**Comment by vegarringdal** [comment]
yes, I prob should move it.
But havent had much time to learn c++, but it is on my todo list.
Would have been nice to have a better understanding of the code.
Just need to make time between all other hobby projects.

Thx for pointing me in the right direction btw. 🥳

**Comment by vegarringdal** [comment]
@cdyk Love the activity, your a machine lately 🥇 👍
